#!/usr/bin/env bash
#Displays `Best School` 10 times but for the 9th iteration it also displays Hi
i=1
while ((i<10))
do
	echo "Best School"
	if ((i == 8))
	then
		echo "Best School"$'\n'"Hi"
	fi
	((i++))
done
