#!/usr/bin/env bash
#Loops 1 to 10 displays `bad luck` for 4th and `good luck` for the 8th and `Best School` for all other iterations
i=
while ((i<10))
do
	if ((i == 3))
	then
		echo "bad luck"
	elif ((i == 7))
	then

		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
