#!/usr/bin/env bash
# Gives information about the `school` file
# Checks if file exists and prints:
# if file exists: `school file exists`
# if file does not exist: `school file does not exist`
# if the file exists print:
# if is empty: `school file is empty`
# if is not empty: `school file is not empty`
# if is a regular file: `school is a regular file`
# if is not a regular file: (nothing)

if [ -e school ]
then
	echo "school file exists"
	if [ -s school ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f school ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
